# Generated by Django 5.2.17 on 2026-10-06 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="nom")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="entreprise active"),
                ),
                (
                    "module_forage",
                    models.BooleanField(default=False, verbose_name="module Forage"),
                ),
                (
                    "module_mine",
                    models.BooleanField(default=False, verbose_name="module Mine"),
                ),
                (
                    "forage_enterprise_id",
                    models.IntegerField(
                        blank=True,
                        help_text="L'id de l'entreprise dans la base de DRILLING-GE.",
                        null=True,
                        verbose_name="enterpriseId côté Forage",
                    ),
                ),
                (
                    "mine_tenant_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="L'identifiant de tenant dans GOOD ENGINEERS OS (ex: 'default' ou un slug).",
                        max_length=120,
                        verbose_name="tenant côté Mine",
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("maj_le", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "entreprise",
                "verbose_name_plural": "entreprises",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="JetonConsomme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jti", models.CharField(max_length=64, unique=True)),
                ("module", models.CharField(max_length=20)),
                ("username", models.CharField(max_length=120)),
                ("emis_le", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "jeton SSO émis",
                "verbose_name_plural": "jetons SSO émis",
                "ordering": ["-emis_le"],
            },
        ),
        migrations.CreateModel(
            name="Profil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_portail",
                    models.CharField(
                        choices=[
                            ("admin", "Administrateur du compte client"),
                            ("membre", "Membre"),
                        ],
                        default="membre",
                        max_length=20,
                    ),
                ),
                (
                    "forage_username",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "forage_role",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "mine_username",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("mine_role", models.CharField(blank=True, default="", max_length=60)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profils",
                        to="portal.entreprise",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "profil",
                "verbose_name_plural": "profils",
            },
        ),
    ]
