# Generated by Django 5.2.18 on 2026-10-07 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=160, verbose_name="nom complet")),
                ("matricule", models.CharField(blank=True, default="", max_length=40)),
                (
                    "poste",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="intitulé de poste",
                    ),
                ),
                (
                    "sous_traitant",
                    models.BooleanField(default=False, verbose_name="sous-traitant"),
                ),
                ("actif", models.BooleanField(default=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employes",
                        to="portal.entreprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "employé",
                "verbose_name_plural": "employés",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Pointage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("present", "Présent"),
                            ("absent", "Absent"),
                            ("conge", "Congé"),
                            ("repos", "Repos"),
                            ("maladie", "Maladie"),
                        ],
                        default="present",
                        max_length=10,
                    ),
                ),
                (
                    "poste",
                    models.CharField(
                        blank=True,
                        choices=[("", "—"), ("jour", "Jour"), ("nuit", "Nuit")],
                        default="",
                        max_length=5,
                    ),
                ),
                (
                    "heures",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pointages",
                        to="portal.employe",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pointages",
                        to="portal.entreprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "pointage",
                "verbose_name_plural": "pointages",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employe", "date"), name="pointage_unique_employe_date"
                    )
                ],
            },
        ),
    ]
